services:
  db:
    image: postgres:15-alpine
    container_name: desafio-seplag-2026-db
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: music123
    ports:
      - 5656:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d music_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: desafio-seplag-2026-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data

  backend:
    build: ./backend
    container_name: desafio-seplag-2026-backend
    ports:
      - "3000:3000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/music_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: music123
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_URL: http://localhost:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET_NAME: music-files
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: desafio-seplag-2026-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  minio_data:
  postgres_data:
