services:
  db:
    image: postgres:15-alpine
    container_name: desafio-seplag-2026-db
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: music123
    ports:
      - 5656:5432

  minio:
    image: minio/minio
    container_name: desafio-seplag-2026-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
